---
name: first
on: [push]
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      run: "date"
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
    - name: Step one
      run: "date /T"
  job2:
    name: Second job
    runs-on: macos-latest
    steps:
    - name: Step one
      run: "date /T"
  job4:
    name: Second job
    needs: [job1 job2 job3]
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      run: "date"
