---
name: Build Dockerfile
on: [push]
jobs:
  job1:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      use: action/checkout@v2
    - name: Show files
      run: "ls -lart ."
    - name: Build Image
      run: "docker build ."
      
  job2:
    name: Test Docker Image
    runs-on: ubuntu-latest
    steps:
    - name: Hello
      run: echo "Hello world!"
  
